apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
archiveSize: 32
mirror:
  operators:
    # --- Red Hat Operators Index (v4.19) ---
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
        - name: kubernetes-nmstate-operator
          channels:
            - name: stable
        - name: kubevirt-hyperconverged
          channels:
            - name: stable
        - name: lvms-operator
          channels:
            - name: stable-4.19
        - name: nfd
          channels:
            - name: stable
        - name: openshift-gitops-operator
          channels:
            - name: latest
        - name: openshift-pipelines-operator-rh
          channels:
            - name: latest
        - name: rhbk-operator
          channels:
            - name: stable-v26.6
        - name: rhods-operator
          defaultChannel: stable-2.22
          channels:
            - name: stable-2.22
        - name: serverless-operator
          channels:
            - name: stable
        - name: servicemeshoperator
          channels:
            - name: stable

    # --- Certified Operators Index (v4.19) ---
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.19
      packages:
        - name: gpu-operator-certified
          channels:
            - name: v26.7
            - name: v26.3
